import math #module used for mathematical calculations
import random #module used to generate random numbers


print("\n")
print("\t\t\t---Please Use Integer as Input, Alphabet is not accepted---") #ALERT

lower = int(input("Enter Lower Limit: ")) #asks to input number of lower limit
upper = int(input("Enter Upper Limit: ")) #asks to input number of upper limit


x = random.randint(lower, upper) #generates random number as per the limits provided by user
print("\n\tYou've only ",round(math.log(upper - lower + 1, 2)), " chances to guess the integer!\n") #displays number of chances

count = 0

#calculation of minimum number of guesses depending upon range
while count < math.log(upper - lower + 1, 2):
		count += 1

		guess = int(input("Guess a number:- ")) #asks user to enter their guess 

		if x == guess: #this is executed when your guess is equal to random number generated by computer
			print("Congratulations you did it in ",count, " try")

		elif x > guess: #this is executed when your guess is small then the actual number
			print("You guessed too small!")

		elif x < guess: #this is executed when your guess is high then the actual number
			print("You Guessed too high!")
		
		#this prints the total number if tries you did to guess the number correct
if count >= math.log(upper - lower + 1, 2):
	print("\nThe number is ", x)
	print("\tPlease try again, Better luck next time!")
